### ISSUE TITLE
Im unable to make payments in test mode

### ISSUE THREAD

**Issue by ax4625** [ashhama/wc-bml-mpos-integration#1]
is there any way i can pay from test account before adding the real account details??

**Comment by ashhama** [comment]
> 
> 
> is there any way i can pay from test account before adding the real account details??

Hi,

May i have the exact error details? 

Also do note the following:

1. Make sure 'Enable Test Mode' box is checked in the gateway settings.
2. The provided Test API credentials are entered (Test credentials are different from production) in the BML mPOS API Login/Key Fields.

https://github.com/ashhama/woocommerce-bml-mpos-integration#deployment

We have tested the application on the Test APIs also with numerous themes and configurations and have not noticed any issues as of yet. Do contact me if issues persist.

Thanks,

**Comment by ax4625** [comment]
I tried without entering the test API key. 
Thanks
