### ISSUE TITLE
Wordpress issue

### ISSUE THREAD

**Issue by Awmire** [ashhama/wc-bml-mpos-integration#10]
Once I upload the plugin, it shows an erroe msg,

"Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".

**Comment by angelicioux** [comment]
In your shared hosting, go to cPanel and find/search for Multi PHP Manager/Select PHP Version. Select your domain or sub domain (whatever you are working with), from the dropdown list select PHP 8.1 and apply.
Go back to your uploaded plugin and try to activate the plugin again. 
Hope this helped~

**Comment by ashhama** [comment]
I have also downgraded some of the dependencies due to bml-connect-php not being compatible with later versions of guzzle. Let me know if there are any issues
