### ISSUE TITLE
looking for the my error code

### ISSUE THREAD

**Issue by wadde2020** [ashhama/wc-bml-mpos-integration#2]
Client error: `POST https://......................................................com.mv/public/transactions` resulted in a `401 Unauthorized` response: {"statusCode":401,"message":"Unauthorized","code":"PP-C-004"}

what happen found this code

**Comment by ashhama** [comment]
Hi. Greatly appreciated if can include any screenshots or additional details on where the error occurred. The message appears to be a response from the bank side which we usually observe if the incorrect APP ID / API KEY was entered. Thanks.

**Comment by ashhama** [comment]
Hi. Will be closing this. Please do check the following and let me know if issue persists.

1. APP ID / API KEY is correct
2. Currency Matches on both Woocommerce and BML Gateway end
