### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by hishambiz** [ashhama/wc-bml-mpos-integration#9]
Hi Bro 

I am getting below error, what will be the issue

Client error: `POST https://api.uat.merchants.bankofmaldives.com.mv/public/transactions` resulted in a `401 Unauthorized` response: {"statusCode":401,"message":"Unauthorized","code":"PP-C-004"}

**Comment by ashhama** [comment]
Have downgraded some of the dependencies. Issues should be fixed now. Also do verify if woocommerce currency is set to MVR if paying through MVR in gateway

**Comment by Awmire** [comment]
I am also facing the same issue. 
++++++++++++++++++++++++++++++
Client error: `POST https://api.uat.merchants.bankofmaldives.com.mv/public/transactions` resulted in a `401 Unauthorized` response: {"statusCode":401,"message":"Unauthorized","code":"PP-C-004"}
++++++++++++++++++++++++++++++

Please help me to solve the issue!

**Comment by zaheen** [comment]
I think you can check if you are using correct API key, I mean you have to use production key only with production site, but if you test it with a test key, then it will not work in a production environment.
